ci:
    autofix_commit_msg: |
        [pre-commit.ci] auto fixes from pre-commit.com hooks
    autofix_prs: true
    autoupdate_branch: ''
    autoupdate_commit_msg: '[pre-commit.ci] pre-commit autoupdate'
    autoupdate_schedule: quarterly
    skip: []
    submodules: false
repos:
-   repo: https://github.com/stAItuned/pre-commit-hooks
    rev: 3ad4e71cb4be0c4ebc6818182ef9752e391515b2
    hooks:
    -   id: team-card-validate
    -   id: team-author-name
    -   id: team-team-names
    -   id: team-linkedin-url
    -   id: team-mail-validate
    -   id: team-description-length
    -   id: team-card-propic
    -   id: article-author
    -   id: article-date
    -   id: article-cover
    -   id: article-language
    -   id: article-meta
    -   id: article-target
    -   id: article-title
    -   id: article-topics
    -   id: article-validate
    -   id: article-length
    -   id: article-images
    -   id: article-equations
    -   id: article-slug